export const ROLES = {
  ADMIN: 'ADMIN',
  DOCTOR: 'DOCTOR',
  NURSE: 'NURSE',
  PHARMACIST: 'PHARMACIST',
  CASHIER: 'CASHIER',
  LAB_TECH: 'LAB_TECH',
  RECEPTIONIST: 'RECEPTIONIST',
};

export const PERMISSIONS = {
  PATIENT_READ: 'PATIENT_READ',
  PATIENT_WRITE: 'PATIENT_WRITE',
  APPOINTMENT_BOOK: 'APPOINTMENT_BOOK',
  CONSULTATION_WRITE: 'CONSULTATION_WRITE',
  PRESCRIPTION_WRITE: 'PRESCRIPTION_WRITE',
  LAB_ORDER: 'LAB_ORDER',
  LAB_RESULT_WRITE: 'LAB_RESULT_WRITE',
  PHARMACY_DISPENSE: 'PHARMACY_DISPENSE',
  INVENTORY_MANAGE: 'INVENTORY_MANAGE',
  BILLING_WRITE: 'BILLING_WRITE',
  PAYMENT_RECORD: 'PAYMENT_RECORD',
  USER_MANAGE: 'USER_MANAGE',
  AUDIT_READ: 'AUDIT_READ',
  REPORT_VIEW: 'REPORT_VIEW',
};
